### ISSUE TITLE
Small bug in My_OpenWeather_Test examples.

### ISSUE THREAD

**Issue by Fredy-1** [Bodmer/OpenWeather#1]
First of all thanks your job again!

I found 2 bug in the example code.
Wrong:
`Serial.printf("Connecting to %s\n", SSID);`
Correct:
`Serial.printf("Connecting to %s\n", WIFI_SSID);`

And this is: 
`return ow.iconName(index);`
'class OW_Weather' has no member named 'iconName'

**Comment by Bodmer** [comment]
Thanks, have updated the example.
