### ISSUE TITLE
API key 2023

### ISSUE THREAD

**Issue by JJHontebeyrie** [Bodmer/OpenWeather#1]
I test your new lib, i am asking my followers to use the free keys and i come back to tell you
The 'old' key i have is still working with this new lib

**Comment by Bodmer** [comment]
I have updated the examples since you posted. Make sure you use the latest version.

**Comment by JJHontebeyrie** [comment]
Hail.
Just a word  BINGO !
All keys working, One Call ones, Forecast ones, old ones, new ones , bravo !!!!

**Comment by Bodmer** [comment]
Great, I have created a release.
