### ISSUE TITLE
CA_Cert requirement for Openweather API

### ISSUE THREAD

**Issue by robrecha** [Bodmer/OpenWeather#10]
Hey Bodmer - Thanks for all of your contributions...
I previously used your DarkSky lib on ESP32 and am now migrating to to your OpenWeather library on ESP32. I have an API key and can successfully grab weather via Node Red or Chrome. Problem is I am receiving a "400 Bad request" on the ESP. I noticed that there was previously a CA_Cert key in Darksky but this is not used in your OpenWeather lib. How are you sending on HTTPS without a CA code? Pls. excuse my limited knowledge here.

Below is the header being sent via ESP. If I cut and paste into Chrome (excluding HTTPS/1.1 text), the response is OK:
GET https://api.openweathermap.org/data/2.5/onecall?lat=27.9881&lon=86.9250&units=metric&lang=en&appid=cfd8786e5cd23cac88d7fa8ee571d37e HTTPS/1.1
Host: api.openweathermap.org
Connection: close

Here is the response:
HTTP/1.1 400 Bad Request

Any suggestions?

Thanks in advance,

Rob R

**Comment by robrecha** [comment]
Update: If i send the GET request with "HTTP/1.1" instead of "HTTPS/1.1" it works. I guess my only concern is with security. Is is potential security risk when sending API requests in this way?

**Comment by Bodmer** [comment]
The library ignores the  key pas/fail and carries on.

Are you sayng the examples do not work for you? I have a copy runing fine on an ESP32.

**Comment by robrecha** [comment]
The example did not initially work for me. I got it working by changing the GET command in OpenWeather.cpp. "HTTPS/1.1\r\n" changed to "HTTP/1.1\r\n" per below:
`client.print(String("GET ") + url + " HTTP/1.1\r\n" + "Host: " + host + "\r\n" + "Connection: close\r\n\r\n");`
I am now wondering if this method of non secure HTTP is a security risk. Given the API key is part of a non-encrypted message. Probably not a big deal in this case. It's not like we are transmitting launch codes.

**Comment by Bodmer** [comment]
Which version of the ESP32 board package are you using in your Arduino environment?

**Comment by robrecha** [comment]
Using firebeetle-esp32 board.

**Comment by Bodmer** [comment]
The board package is the software support loaded in the Arduino IDE. Use the boards manager menu option to check the version you have loaded.

**Comment by robrecha** [comment]
Esp32 by expressing version 1.0.4On 25 Sep 2020 19:27, Bodmer <notifications@github.com> wrote:
The board package is the software support loaded in the Arduino IDE. Use the boards manager menu option to check the version you have loaded.

**Comment by Bodmer** [comment]
Examples have been checked and no related issues found.
