### ISSUE TITLE
Prob. of Percipitation

### ISSUE THREAD

**Issue by Lebo77** [Bodmer/OpenWeather#11]
Looking at the OpenWeather API there seems to be a forecast parameter "daily.pop" and "hourly.pop" that contain the probability of precipitation. 

So far as I can tell your library does not retain these values, and it seems that it probably should. If there is some reason they are not included then OK, but they would be useful to me if they could be added. 

Thanks!

**Comment by Bodmer** [comment]
I am guessing this has been added recently.

I have updated the library to store that value.

**Comment by Lebo77** [comment]
Thanks for the SUPER quick turnaround. I was going to add it myself so I could keep working but you beat me to it!
