### ISSUE TITLE
Nullptr in getForecast() causes crashes

### ISSUE THREAD

**Issue by Lebo77** [Bodmer/OpenWeather#13]
Sorry to be a bother, but passing in a null pointer to getForecast() does not seem to work as I get an immediate panic despite this comment in OpenWeather.cpp: "// Pass a nullptr for current, hourly or daily pointers to exclude in response.". I am trying to pass in a nullptr for the hourly dataset with the following code snippet::

```
current = new OW_current;
daily =  new OW_daily;
hourly =  nullptr;
result = ow.getForecast(current, hourly, daily, api_key, latitude, longitude, units, language);
```

**Comment by Bodmer** [comment]
The library has been updated.
