### ISSUE TITLE
change language but still some don't, plus others

### ISSUE THREAD

**Issue by herreran24** [Bodmer/OpenWeather#14]
Hi Bodmer,

1. I was able to make it to work in the first upload (almost all). Then I started to work on the language, but wasn't lucky with the text that should be changed from:

   // For language codes see https://openweathermap.org/current#multi
   const String language = "sp"; // Default language = en = English

I tried es, ES, SP, and also fr, just to check if it was a spanish issue or something, but not, alwasy in english. See the pic attached.
![OpenWeather](https://user-images.githubusercontent.com/59707148/97517486-112d1500-1974-11eb-9725-87597936dcf1.PNG)

2. Also, I was able to see the wind direction circle and direction, but for some reason I'm not seeing it today. I never was able to see the N, S, W, E... but wasn't a big deal. I don't know why I cannot see it today.

3. I'm trying to show somewhere the readings from a BME280, see below, and for debug purposes, I'm able to get it, but I just don't know how to show in a particular site of the screen, for example in the right of the time. (I want to see external (internet) and interior (BME)). Can you tell me how?

#define AA_FONT_SMALL "fonts/NotoSansBold15" // 15 point sans serif bold
#define AA_FONT_LARGE "fonts/NotoSansBold36" // 36 point sans serif bold
/***************************************************************************************
**                          Load the libraries and settings
***************************************************************************************/
//Incluir BME280 librerias----------------
**#include <Wire.h>
#include <Adafruit_BME280.h>
#include <Adafruit_Sensor.h>
#define SEALEVELPRESSURE_HPA (1013.25)
Adafruit_BME280 bme; // I2C**
//----------------------------------------

...
...
...

/***************************************************************************************
**                          Setup
***************************************************************************************/
void setup() {
  Serial.begin(250000);

//Setup BME280----------------------
  bool status;
  **if (!bme.begin(0x76)) {
    Serial.println("BME280 not found!");
    while (1);**
    //delay(2000);
  }
  //----------------------------------

...
...
...
**Within NTP_time.h:**
//====================================================================================
// Decode the NTP message and print status to serial port
//====================================================================================
void decodeNTP(void)
{
  timeValid = false;
  uint32_t waitTime = millis() + 500;
  while (millis() < waitTime && !timeValid)
  {
    yield();
    if (udp.parsePacket())
    {
      newRecvTime = millis();

      // We've received a packet, read the data from it
      udp.read(packetBuffer, NTP_PACKET_SIZE); // read the packet into the buffer

      Serial.print("\nNTP response time was : ");
      Serial.print(500 - (waitTime - newRecvTime));
      Serial.println(" ms");

      Serial.print("Time since last sync is: ");
      Serial.print((newRecvTime - lastRecvTime) / 1000.0);
      Serial.println(" s");
      lastRecvTime = newRecvTime;

      **Serial.println(bme.readTemperature());** //---------------------------------------------------------
![Captura2](https://user-images.githubusercontent.com/59707148/97517515-20ac5e00-1974-11eb-95d1-00e5eec16cea.PNG)

**Comment by herreran24** [comment]
Update: forget the wind issue, I fixed, something I changed that shouldn't

**Comment by Bodmer** [comment]
It looks like the "Main" response does not get changed to the local language:
```

weather |  
-- | --
0 |  
id | 802
main | "Clouds"
description | "nubes dispersas"
icon | "03n"
base | "stations"

```
The simple solution is to [change this line](https://github.com/Bodmer/OpenWeather/blob/master/examples/TFT_eSPI_OpenWeather/TFT_eSPI_OpenWeather.ino#L342), to:

```
  String weatherText = current->description;
```

**Comment by Bodmer** [comment]
You may also have to[ uncomment these lines](https://github.com/Bodmer/OpenWeather/blob/master/OpenWeather.cpp#L586-L587) if you are using the partial data set.

**Comment by herreran24** [comment]
That didn't work, but for saving time I did a workaround, looked at the results list in openweathermap and translate them, is not the best, but works :)

...
 if (current->main == "Thunderstorm"){
      Translate="Tormenta";
    }
    else if (current->main == "Clear"){
      Translate="Claro";
    }
...
    String weatherText = Translate;
  //String weatherText = current->description;

Also, included the internal temperature (inside the house) and change m/s to km/h, since we don/t use m/s.
  weatherText = (uint16_t)current->wind_speed * **3.6**; //

![Captura](https://user-images.githubusercontent.com/59707148/97772148-f3ea7900-1b22-11eb-9d73-9dd455657b17.jpeg)


Let me tell you that you did an awasome work!

**Comment by herreran24** [comment]
I just need to figure it out how to include the max temperature in the actual day.

**Comment by Bodmer** [comment]
The suggested changes do work. Note that two files must be changed as detailed above, (OpenWeather.cpp and your sketch). Example output:

![OW](https://user-images.githubusercontent.com/15824805/97781159-7570f400-1b81-11eb-8c59-4ea57d28b759.jpg)

I see you have the wind direction icon back. You may have lost this because not enough SPIFFS space was allocated (2MBytes needed as noted in the sketch header), otherwise one of your edits probably caused the problem.

I will update the library so that the description field is used if the language is not "en".

**Comment by Bodmer** [comment]
I have update the library so that the description field is used if the language is not "en".
