### ISSUE TITLE
Problems to compile

### ISSUE THREAD

**Issue by HWH53** [Bodmer/OpenWeather#15]
Hello,
the code compiles without any problems with the _Arduino IDE for ESP8266_!!
Ich work with _VScode and PlatforformIO and the arduino framework_. The same Code, running perfect on Arduino IDE for the same controller, abborts during compile with a lot of Errors and warnings. 
Are there any Changes needed? 
I'm a newbee in programming. Can anyone help me to solve this Problem please?

greetings
Helmut

**Comment by Bodmer** [comment]
Marked as help wanted. The library relies on the Arduino support packages so maybe you do not have them linked in.

The simplest option is to use it with the Arduino IDE.

**Comment by HWH53** [comment]
I think the basic Arduino Supportfiles are included in the used Arduino Framework. The needed external Libraries are autmatic downloaded and installed at the begin of the compile.prozess by entries in the platformio.ini File. It seems the compiler can't handel some funktions. I think it happens bevore the linker prozess begins.
I can't find the Problems because of my low experiences. I'll try to learn in programming and i'm very thanfull for anykind of help.

geetings 
Helmut

**Comment by Bodmer** [comment]
I can only help when used with the Arduino IDE. That is ideal for learning.
