### ISSUE TITLE
TFT_eSPI_OpenWeather_LittleFS: Only white screen after Wifi login

### ISSUE THREAD

**Issue by ulihuber** [Bodmer/OpenWeather#16]
I tried to run this on an esp32-2432s028 board, but after the splash screen, and 'connecting to WiFi' there is only a white screen.
The board should run OK, it is tested with various examples from the TFT_eSPI library.
I checked the access to the bmp files with debugging print and can't find a problem there too:
`***********in drawBmp
/icon/partly-cloudy-day.bmp
***********read16(bmpFS) == 0x4D42 --> OK
*************BMP end
***********in drawBmp
/wind/NW.bmp
***********read16(bmpFS) == 0x4D42 --> OK
*************BMP end`
I think there is an issue with the configuration of the TFT_eSPI library, but I can't find it :-(
Any help is greatly appreciated.
Uli

**Comment by Bodmer** [comment]
What size is you LittleFS partition?

**Comment by ulihuber** [comment]
I have changed the code to SD, because my Arduino IDE 2 does not allow to send files to LittleFS. So no partition issue. Debug statements also show that the picture  files are found and processed.
Could there be a conflict with HSPI/VSPI?
Edit - Validated:  The display goes white with and disfuctional exactly with the WiFi start. But stil no clue why...
I found the following statement in discussions:

> _Answered my own question: The problem was the use of GPIO2 for T_DO and MISO. It seems to be used when the Wifi Interface is turned on for some reason. Since the Display is not really using MISO, it was still working. However, since the touch interface uses the T_DO signal, it was malfunctioning. Connecting to another GPIO (GPIO23 in this case) solved the problem_.

If this is true and the found schematics are correct,  I might not use the esp32-2432s028 board as the display connection is as follows:
![grafik](https://github.com/Bodmer/OpenWeather/assets/33638335/2d81854c-b51b-4890-b6f2-bcb609f1eb34)
This is in conflict with:

> ADC2 (10 channels, attached to GPIOs 0, 2, 4, 12 - 15 and 25 - 27). However, the usage of ADC2 has some restrictions for the application:   ADC2 is used by the Wi-Fi driver. Therefore the application can only use ADC2 when the Wi-Fi driver has not started.

**Comment by ulihuber** [comment]
To proof the theory above, I tested another sketch (SD_Jpg.ino from TJpg_Decoder examples) with added WiFi configuration. No problem there. I am running out of ideas :-(

**Comment by ulihuber** [comment]
Solved. :-O
I changed from WROOM-32D (which is stated on the module....) to DOIT ESP32 DevKit V1.
Now it works without any problems.
Sorry for bothering with this issue.
