### ISSUE TITLE
Moonphase may i use

### ISSUE THREAD

**Issue by ldijkman** [Bodmer/OpenWeather#19]
Hello 

Meet you again ;-)
Was searching for moonphase for my thermostat

May i use less or more  code from you
Om my thermostat 
If i place your license texy in your part off the code, maybe seperate header file

Luberth

Esp32 smart thermostat
Http://www.arduino.tk

**Comment by Bodmer** [comment]
I don't think the license needs to follow it because the code segment is so small.

The moon phase algorithm [came from here](http://www.voidware.com/moon_phase.htm) and I created very little code to use it.
