### ISSUE TITLE
Taggs

### ISSUE THREAD

**Issue by mats-nk** [Bodmer/OpenWeather#2]
Could you start to use tags (versions) then your lib could be added Arduino, so it gets into the "pick and choose" libraries in the Arduino IDE.

**Comment by mats-nk** [comment]
And thank for your inspiring work, I will use it in my "Visa" project :-)

`https://github.com/mats-nk/Visa`

**Comment by Bodmer** [comment]
Released latest at 0.3.0

**Comment by mats-nk** [comment]
Now its included in the official Arduino library registry!

https://github.com/arduino/library-registry/pull/2485
