### ISSUE TITLE
Parsing JSON stopps working

### ISSUE THREAD

**Issue by Xudefang** [Bodmer/OpenWeather#20]
Hi

This code was cobbled together just to show the problem. After the initial API collection the ESP 32 collects data from a 8266 with sensors which works nicely. Most of the time though after contacting Openweather again which is also successful the last operation is Parsing JSON after which the ESP32 crashes by doing nothing until it is reset.

[Arkiv.zip](https://github.com/Bodmer/OpenWeather/files/5895951/Arkiv.zip)

Best regards Stefan

**Comment by Bodmer** [comment]
I tried to run the cobbled together sketch! I had to comment out the Moon stuff. Then got this error:
```
exit status 1
too many arguments for format [-Werror=format-extra-args]
```
on this line:
```
  Serial.printf("Rainsensor.1f \n", boardsStruct[myData.id - 6].r, DEC);
```

Perform some debugging and try to identify where the problem originates in more detail.

**Comment by Bodmer** [comment]
More line would not compile, I commented out these three lines, then the sketch would compile and upload:
```
  //Serial.printf("Illumination is %.1f \n", boardsStruct[myData.id - 4].l, DEC);
  //Serial.printf("Runtime is %.1f \n", boardsStruct[myData.id - 5].m);
  //Serial.printf("Rainsensor.1f \n", boardsStruct[myData.id - 6].r, DEC);
```

It has run for more than 10 minutes and fetched the weather a few times without crashing. How long do you have to wait for it to crash? What is the last thing it prints before crashing?

**Comment by Bodmer** [comment]
It has been running for 40 minutes and fetched the weather many time, so I am not sure I can help based on this example.

Have you tried using the ESP32 Exception Decoder tool in the Arduino IDE? (You have to add this).

**Comment by Bodmer** [comment]
I am guessing you have identified the problem and fixed it. Report back if you are still having issues.

**Comment by Xudefang** [comment]
Hi 

The issue is still there, I have collected a dump from the serial monitor although I edited out some data from sent from the 8266 just because of the amount of repeated data, I have also nicked the sensor which is why there are a lot of zeros. And of course a new zip with the code used to get the serial monitor. The end of the log from the print out shows where the ESP32 stops. And the sketch with which the data from the serial monitor was generated. I also added the sketch which is running on the 8266 which sends the data to the ESP32. All codes run on my ESP32 DOIT Devkit V1 and 8266. I'll try the ESP32 Exception Decoder during next week.

Thanks for your help.


[Node_MCU_Weath_sender_v4_with_BME280.ino.ino.zip](https://github.com/Bodmer/OpenWeather/files/5900688/Node_MCU_Weath_sender_v4_with_BME280.ino.ino.zip)

[Arkiv.zip](https://github.com/Bodmer/OpenWeather/files/5900682/Arkiv.zip)

[Connected.pdf](https://github.com/Bodmer/OpenWeather/files/5900671/Connected.pdf)

**Comment by Xudefang** [comment]
Hi again


the issue is still there. I am sending you code from the 8266 that send data to the ESP 32 and a PDF from the serial monitor that shows where the ESP32 stops working. I have not tested the ESP32 Exception Decoder but will give it a go during the week. The PDF from the serial monitor was slightly edited as the 8266 managed to send information a lot of times. The reason of the 0 degree C etc is due to a missing BME280 sensor which is currently used on another project. 

Thanks for your help.

[Arkiv.zip](https://github.com/Bodmer/OpenWeather/files/5900717/Arkiv.zip)
[Connected.pdf](https://github.com/Bodmer/OpenWeather/files/5900719/Connected.pdf)
[Node_MCU_Weath_sender_v4_with_BME280.ino.ino.zip](https://github.com/Bodmer/OpenWeather/files/5900720/Node_MCU_Weath_sender_v4_with_BME280.ino.ino.zip)
