### ISSUE TITLE
no bmp show

### ISSUE THREAD

**Issue by Maddin4000** [Bodmer/OpenWeather#21]
Hi Bodmer, i have all installed, downgrade to Arduino 1 to upload Spiffs; upload ok but no Bitmaps seen on screen ???

ESP32 wroom, ili9341,Mac OSX,

**Comment by Bodmer** [comment]
Get the TFT__eSPI examples working with the screen first.

**Comment by Maddin4000** [comment]
I have test all 

what do I upload to spiffs? In the sketch folder is your data folder only that ?

**Comment by Bodmer** [comment]
Yes, the upload should automatically use files in the data folder. Note that some examples use LittleFS.

**Comment by Bodmer** [comment]
Look at the serial monitor output to see debug messages.

**Comment by Maddin4000** [comment]
E (367) esp_littlefs: mount failed,  (-84)
E (368) esp_littlefs: Failed to initialize LittleFS

SPIFFS files found:
Listing directory: /
Failed to open directory

Font file fonts/NotoSansBold15 not found!
.

NTP response time was : 29 ms
Time since last sync is: 6.57 s
Received NTP UTC time : 15:18:23
Font file fonts/NotoSansBold15 not found!
Font file fonts/NotoSansBold15 not found!


The connection to server is secure (https). Certificate not checked.

Sending GET request to api.openweathermap.org port 443
Header end found

Parsing JSON

Done in 1144 ms

Data points received
Free heap = 251376
Font file fonts/NotoSansBold15 not found!
Font file fonts/NotoSansBold15 not found!
 File not found
 File not found
 File not found
 File not found
 File not found
 File not found
 File not found
Font file fonts/NotoSansBold36 not found!
Font file fonts/NotoSansBold36 not found!
Font file fonts/NotoSansBold36 not found!

**Comment by Maddin4000** [comment]
now I fix it with littles plugin. 

only fonts not loaded?


thx

**Comment by Maddin4000** [comment]
i change to fonts.h now all works fine

**Comment by superceleron** [comment]
> i change to fonts.h now all works fine

so where did you do that change? since im also having the same issue.

**Comment by Maddin4000** [comment]
In Arduino Files included Lieben Gruß Martin HilbrandtAm 19.01.24 um 15:07 schrieb LuisG
                
            
            
                
                    Von: "LuisG" ***@***.***>Datum: 19. Januar 2024An: "Bodmer/OpenWeather" ***@***.***>Cc: "Author" ***@***.***>,"Maddin4000" ***@***.***>Betreff: Re: [Bodmer/OpenWeather] no bmp show (Issue #21)
                
                

i change to fonts.h now all works fine

so where did you do that change? since im also having the same issue.

**Comment by superceleron** [comment]
Thks
