### ISSUE TITLE
Errors compiling OpenWeather.cpp

### ISSUE THREAD

**Issue by gmkyte** [Bodmer/OpenWeather#21]
Hi, I am receiving multiple error, all appear connected, when compiling OpenWeather.cpp on the Arduino IDE 1.8.13. The error appears to be related to the declaration of ParseRequest and ParseRequestSecure in relation to being in scope, This is the error printout:

C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp: In member function 'bool OW_Weather::parseRequest(String)':
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp:178:45: error: 'parseRequestSecure' was not declared in this scope
   if (Secure) return parseRequestSecure(&url);
                                             ^
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp:179:40: error: 'parseRequestInsecure' was not declared in this scope
   else return parseRequestInsecure(&url);
                                        ^
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp: At global scope:
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp:182:48: error: no 'bool OW_Weather::parseRequestSecure(String*)' member function declared in class 'OW_Weather'
 bool OW_Weather::parseRequestSecure(String* url) {
                                                ^
C:\Users\Library\Documents\Arduino\libraries\OpenWeather-master\OpenWeather.cpp:267:50: error: no 'bool OW_Weather::parseRequestInsecure(String*)' member function declared in class 'OW_Weather'
 bool OW_Weather::parseRequestInsecure(String* url) {

I am not clear where the error is and must be missing something I think. I am compiling for a WEMOS D1 Mini (8266) and have been successfully running the DarkSky version of your excellent project without any issues. Would appreciate your thoughts thanks.

**Comment by Bodmer** [comment]
I have made some changes recently for the ESP32 it looks like I have introduced a problem. I will investigate.

**Comment by Bodmer** [comment]
I have fixed it. I for got yo upload an updated file.

Thanks for reporting this.

**Comment by gmkyte** [comment]
Thank you very much!

**Comment by Ricvice** [comment]
I have tryed and tryed to download the sketch and keep getting MULTIPLE errors. Have they been any updated code to solve this?

**Comment by Bodmer** [comment]
This repository is an Arduino library with examples. It is for ESP32 and ESP8266 only. The library is up to date and works fine on my setups.
