### ISSUE TITLE
Millis instead of Delay

### ISSUE THREAD

**Issue by lon3wolf2k** [Bodmer/OpenWeather#23]
Hi and congrats for the sketch and library. Is it possible to use millis instead of delay to fetch openweathermap data? The reason is im using a ntp and dht22 to display local time and room temp and humidity and cycle the info on an oled screen along with 3 days forecast from your library, but delay freezes the whole cycle. Im using an Esp8266 and My_OpenWeather_Test.ino
Thanks!

**Comment by Bodmer** [comment]
Yes, the example can be modified, the delay is just there  to limit the calls per day for testing.
