### ISSUE TITLE
Won't Load Graphics

### ISSUE THREAD

**Issue by Jeff5263** [Bodmer/OpenWeather#24]
I got this running on my ESP8266 but it won't load graphics. I'm getting the fonts okay.

**Comment by Bodmer** [comment]
I am guessing that not enough space has been allocated for the SPIFFS partition. You need to allocate at least 2MBytes to SPIFFS in the IDE, and then upload again.

**Comment by Bodmer** [comment]
Assumed fixed now. Closing.
