### ISSUE TITLE
No weather data

### ISSUE THREAD

**Issue by papsten** [Bodmer/OpenWeather#26]
After several days, getting data from openweather with secure https connection stopped working, with message 'Connection failed' on the serial output. Changing port number in OpenWeather.cpp from 443 to 80, and 'WiFiClientSecure client' to 'WiFiClient client' made the esp32 connect again, but i still don't know why it cannot connect through https anymore . . . .

**Comment by OstertagM** [comment]
seams to be a problem with the SSL certification... other user has also some problems but how to fix I don't know.

**Comment by Bodmer** [comment]
Not sure if this is related but I found that ESP32 board package 1.0.5 (loaded via the Arduino IDE) fails the SSL client certification, but board package 1.0.4 works OK.

Which board package are you using?

**Comment by Bodmer** [comment]
ESP32 board package 1.0.4 debug output (Core Debug Level: Verbose):

```
The connection to server is secure (https).
[V][ssl_client.cpp:56] start_ssl_client(): Free internal heap before TLS 250124
[V][ssl_client.cpp:58] start_ssl_client(): Starting socket
[V][ssl_client.cpp:93] start_ssl_client(): Seeding the random number generator
[V][ssl_client.cpp:102] start_ssl_client(): Setting up the SSL/TLS structure...
[I][ssl_client.cpp:156] start_ssl_client(): WARNING: Use certificates for a more secure communication!
[V][ssl_client.cpp:180] start_ssl_client(): Setting hostname for TLS session...
[V][ssl_client.cpp:195] start_ssl_client(): Performing the SSL/TLS handshake...
[V][ssl_client.cpp:216] start_ssl_client(): Verifying peer X.509 certificate...
[V][ssl_client.cpp:225] start_ssl_client(): Certificate verified.
[V][ssl_client.cpp:240] start_ssl_client(): Free internal heap after TLS 205008
Sending GET request to api.openweathermap.org port 443
[V][ssl_client.cpp:279] send_ssl_data(): Writing HTTP request...
Header end found

Parsing JSON
[V][ssl_client.cpp:248] stop_ssl_socket(): Cleaning SSL connection.

Done in 1252 ms
[V][ssl_client.cpp:248] stop_ssl_socket(): Cleaning SSL connection.
[V][ssl_client.cpp:248] stop_ssl_socket(): Cleaning SSL connection.
Data points received
Free heap = 251312
```

ESP32 board package 1.0.5 debug output (Core Debug Level: Verbose):
```
The connection to server is secure (https).
[V][ssl_client.cpp:59] start_ssl_client(): Free internal heap before TLS 264632
[E][WiFiClientSecure.cpp:127] connect(): start_ssl_client: -1
[V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
Connection failed.
[V][ssl_client.cpp:265] stop_ssl_socket(): Cleaning SSL connection.
Failed to get data points
Free heap = 266828
Failed to get weather
```

**Comment by pfennich** [comment]
Hi, I am having the same issue and went to the ESP32 source code to identify the reason of the start_ssl_client: -1 return.
Here is my observations:
The WifiClientSecure should be used at least by providing the Root CA using the SetCACert to authenticate the server.

in the code the condition is met to exit with -1.
int start_ssl_client(sslclient_context *ssl_client, const char *host, uint32_t port, int timeout, const char *rootCABuff, const char *cli_cert, const char *cli_key, const char *pskIdent, const char *psKey, bool insecure)
{
    char buf[512];
    int ret, flags;
    int enable = 1;
    log_v("Free internal heap before TLS %u", ESP.getFreeHeap());

    if (rootCABuff == NULL && pskIdent == NULL && psKey == NULL && !insecure) {
        return -1;
    }

I did a test using a simple http client using an https query to OpenWeatherMap api and I was able to retrieve the json file that the app should be retrieving. 
I presume that the code was changed by introducing the &&!insecure that is making the connection to fail. 

If this helps

**Comment by pfennich** [comment]
I have changed the local code by adding the instruction 
 client.setInsecure();//skip verification before any 

if(!client.connect(host, port))........

affected methods are parseRequestInsecure and parseRequest

and it is back working

**Comment by Bodmer** [comment]
I have updated the library to invoke no certificate checking, this is now the same as the ESP8266.

I suspect at 1.0.4 that is no certificate was provided it defaulted to not checking it and carried on.

Thanks for reporting this and the fix, hopefully all is well now.

**Comment by papsten** [comment]
Thanks for your information and change of the library, Bodmer. I will load and try the new library later.

Regards, Papsten

Verzonden vanuit Mail<https://go.microsoft.com/fwlink/?LinkId=550986> voor Windows 10

Van: ***@***.***>
Verzonden: zondag 14 maart 2021 01:48
Aan: ***@***.***>
CC: ***@***.***>; ***@***.***>
Onderwerp: Re: [Bodmer/OpenWeather] No weather data (#26)


I have updated the library to invoke no certificate checking, this is now the same as the ESP8266.

I suspect at 1.0.4 that is no certificate was provided it defaulted to not checking it and carried on.

Thanks for reporting this and the fix, hopefully all is well now.
