### ISSUE TITLE
TFT_eSPI_Openweather displays time 10 minutes in the past

### ISSUE THREAD

**Issue by rjshiffer** [Bodmer/OpenWeather#28]
TFT_eSPI_Openweather displays time 10 minutes in the past if an NTP packet
from the time server arrives after 500ms. 

My TFT_eSPI_Openweather display runs flawlessly for days at a time, until
the time suddenly shows 10 minutes in the past and remains 10 minutes in the 
past.  I discovered that this happens when an NTP packet from the time server
arrives after the 500ms wait time.

After a NTP packet does not arrive within 500ms, the code issues message

     No NTP reply, trying again in 1 minute...

Ten minutes later (not 1 minute per the message), syncTime() is called. After
sending a new request via sendNTPpacket(), to the time server, decodeNTP() reads
the previously delayed packet from the time server.   This previous packet has
the time 10 minutes in the past.  From this point on, the code is always one packet
behind the current one.  The message showing the NTP UTC time also
shows the past time. For example (notice fast response time):

     NTP response time was : 2 ms
     Time since last sync is: 600.06 s
     Received NTP UTC time : 3:45:00    <<---<< This time also has past time

I verified this by changing the NTP packet delay time from 500ms to 50ms to 
cause the error to occur more frequently.  (My time server normally responds
between 30-60ms).

I solved the problem by adding this code prior to calling sendNTPpacket() to 
clear all old packets:

    while  (udp.parsePacket() > 0)  {                             // Is a packet there?
        Serial.println("Reading delayed NTP packet.");   // Yes
        udp.read(packetBuffer, NTP_PACKET_SIZE);       // read the packet into the buffer
    }

Thanks much for the TFT_eSPI library.  It's used in all my projects.

**Comment by Bodmer** [comment]
Ah! Thanks for spotting this.

I will test and update the library.

**Comment by Bodmer** [comment]
Works fine so uploaded the fix. Thanks.
