### ISSUE TITLE
icons from sd card

### ISSUE THREAD

**Issue by pipikupi** [Bodmer/OpenWeather#31]
My new plan is to move to ssd1963 7inch screen with biger icons and esp32 has not enough of spiffs so idea is to keep fonts in spiffs but move icons to sd card. could you give me any idea how to start with that case. Shall be very appreciated for any support

**Comment by Bodmer** [comment]
It is possible but first consider using 8 bit BMP files with a colour palette. This will at least halve the file sizes and icons typically have a limited colour set. See [discussion here](https://github.com/Bodmer/TFT_eSPI/issues/941#issuecomment-761863243) and the replacement BMP code.

There are unused lines applicable for SD jpeg files, [for example here](https://github.com/Bodmer/OpenWeather/blob/master/examples/TFT_eSPI_OpenWeather/GfxUi.cpp#L165). As the code came from the Jpeg decoder library which has SD card examples.

**Comment by Bodmer** [comment]
In general it is a case of replacing SPIFFS. with SD. but I do not have time to look at in detail.

**Comment by pipikupi** [comment]
Thank you I will look at that.
