### ISSUE TITLE
Adding other forecast data

### ISSUE THREAD

**Issue by hcg1967** [Bodmer/OpenWeather#32]
Not being a programming specialist by any means I’ve been trying to display additional forecast data such as windspeed, wind direction and air pressure in addition to the 4 day weather icons and min/max temperatures that are currently being displayed. Assuming these data should be retrievable from the json string as well, but so far I’ve been unsuccesful; these data now only appear as zero values on my display (“0”). Browsing through the several pieces of code I haven’t been able to figure this out yet. Any hints or tips would be highly appreciated.

**Comment by Bodmer** [comment]
Assuming that you are running [the example here](https://github.com/Bodmer/OpenWeather/tree/master/examples/TFT_eSPI_OpenWeather) then the additional data should already be displayed.

You can see the jason data to check if the weather report is sending the wind and pressure information [by uncommenting this line](https://github.com/Bodmer/OpenWeather/blob/master/User_Setup.h#L16).

**Comment by hcg1967** [comment]
Yes, I am running the TFT_eSPI_OpenWeather example. Uncommenting _//#define SHOW_JSON_  in User_Setup.h shows all data being retrieved indeed. Then I uncommented _//#define SERIAL_MESSAGES_ in TFT_eSPI_OpenWeather.ino and added a _Serial.print("pressure           : "); Serial.println(daily->pressure[i]);_ to the printWeather procedure. It is at this point that I'm stuck as it only returns zero's.  Tried same for wind_speed and wind_deg, but I only get zero's whereas the json has actual values indeed. I am just probably silly and overlooking something very obvious.

json output:
.....
{"dt":1619348400,"sunrise":1619324923,
"sunset":1619377078,"moonrise":1619368980,"moonset":1619323920,"moon_phase":0.43,"temp":
{"day":8.79,"min":5.14,
"max":8.89,"night":6.85,"eve":7.36,"morn":5.14
},"feels_like":
{"day":5.39,"night":1.15,"eve":2.95,"morn":1.15
},
"pressure":1028,"humidity":59,"dew_point":1.12,"wind_speed":9.51,"wind_deg":24,"wind_gust":10.66,"weather":
[
{"id":800,
"main":"Clear","description":"clear sky","icon":"01d"
}
],"clouds":5,"pop":0,"uvi":5.43
},
........

serial output:

###############  Daily weather  ###############

dt (time)          : Apr 25 12:00
id                 : 800
temp_max           : 8.89
temp_min           : 5.14
pressure           : 0.00
wind_speed         : 0.00
wind_deg           : 0

**Comment by Bodmer** [comment]
OK, Iunderstand what you wish to do now.

The TFT_eSPI only stores the subset of the data needed to save memory. To collect the full set you need to [change this line 163](https://github.com/Bodmer/OpenWeather/blob/master/examples/TFT_eSPI_OpenWeather/TFT_eSPI_OpenWeather.ino#L163) to:
```
  ow.partialDataSet(false);
```

**Comment by hcg1967** [comment]
Got it working now. Instead of pulling the full dataset, I expanded the partialDataset by uncommenting the lines I needed. Works like a charm.  Many thanks for your support!!
