### ISSUE TITLE
LittleFS

### ISSUE THREAD

**Issue by podaen** [Bodmer/OpenWeather#36]
Where can I find the littleFS library for the esp32?

**Comment by podaen** [comment]
It seems it doesn't exists for the esp32. Than I suspect have to base me on SPIFFS... 

https://github.com/Bodmer/OpenWeather/tree/master/examples/TFT_eSPI_OpenWeather

Would it make any difference?

**Comment by Bodmer** [comment]
LittleFS is built into the latest ESP32 Arduino board package 2.0.x.

Although LittleFS is faster  and SPIFFS is deprecated, you will find SPIFFS is fine for the weather library.

**Comment by podaen** [comment]
the jpeg decoder is using LittleFS. Can I just comment it?

https://github.com/Bodmer/TJpg_Decoder/blob/master/src/TJpg_Decoder.h

**Comment by Bodmer** [comment]
The SPIFFS example use a different jpeg decoder library. Which example are you trying to run?

**Comment by podaen** [comment]
I only use parts of it. The example of comment 2

> It seems it doesn't exists for the esp32. Than I suspect have to base me on SPIFFS...
> 
> https://github.com/Bodmer/OpenWeather/tree/master/examples/TFT_eSPI_OpenWeather
> 
> Would it make any difference?

**Comment by podaen** [comment]
The GfxUi.h is using it.

**Comment by podaen** [comment]
This is what I found for the esp32 to use littlefs

https://www.arduino.cc/reference/en/libraries/littlefs_esp32/

It has an other name. I diden't tried to use it.

**Comment by Bodmer** [comment]
I suggest you use the [SPIFFS based example](https://github.com/Bodmer/OpenWeather/tree/master/examples/TFT_eSPI_OpenWeather) and [this JPEGDecoder library](https://github.com/Bodmer/JPEGDecoder) is then used which supports SPIFFS. You can use TFT_eSPI v 2.3.70 with the ESP32 1.0.x board package.

Alternatively, [load the latest ESP32 2.0.x board package ](https://docs.espressif.com/projects/arduino-esp32/en/latest/installing.html)with LittleFS built in and then use [this example](https://github.com/Bodmer/OpenWeather/tree/master/examples/TFT_eSPI_OpenWeather_LittleFS). You can then use the alternative [TJpg_Decoder library here](https://github.com/Bodmer/TJpg_Decoder) which supports SPIFFS and LittleFS.

**Comment by podaen** [comment]
I can not do... I have to stay with the 1.0.6. I will take the latest version. Thanks

**Comment by podaen** [comment]
Sorry, I misunderstood. I was still using the TJpg_Decoder, I corrected it.
