### ISSUE TITLE
Add a discusions tab?

### ISSUE THREAD

**Issue by ldijkman** [Bodmer/OpenWeather#39]
my issue ?  ;-)

Maybe Add a discusions tab?

Oh this should be installable from browser
Ace js cloudeditor could maybe edit a config.txt for time lon lat openweather  apikey

https://github.com/ldijkman/randomnerd_esp32_wifi_manager/tree/main/ESP8266-TFT_eSPI

![20220417_085338](https://user-images.githubusercontent.com/45427770/163704146-f62e8802-f3ac-44c4-85fa-6cd028bad5b5.jpg)

![20220417_101552](https://user-images.githubusercontent.com/45427770/163709928-e7aaf202-ec09-44ee-b752-3ef3580b6a52.jpg)

**Comment by Bodmer** [comment]
Issues only on this repository to reduce maintenance load!
