### ISSUE TITLE
Jpg icons versus bmp saves +/- 700kb littlefs

### ISSUE THREAD

**Issue by ldijkman** [Bodmer/OpenWeather#40]
Hello

Jpg icons versus bmp saves +/- 700kb littlefs
Or did you have a reason to use bmp icons?

https://github.com/ldijkman/OpenWeather

**Comment by Bodmer** [comment]
No, apart from compression artifacts which affect the black areas when using black as the transparent colour in other sketch variants. Storage resources were not considered as being a problem.
If I updated the library I would use lossless png compressed images.

**Comment by Bodmer** [comment]
I tried using a PNG image decoder on the ESP8266 and it does not have sufficient RAM. The other supported processors work fine.

So if extra icons are wanted and FLASH memory limits become a problem then your solution of using jpegs is good.

**Comment by ldijkman** [comment]
hello

i have youre code and mine a bit combined
can make it installable  from webbrowser => esp web tools
api key and location can be edited from ace js cloudeitor  http mdns or ip /edit config.txt

but i have some rebooting with my code

https://github.com/ldijkman/randomnerd_esp32_wifi_manager/blob/main/ESP8266-TFT_eSPI/ESP8266-LittleFS-wifi-manager_with_editor/ESP8266-LittleFS-wifi-manager_with_editor.ino


ESP Web installer https://ldijkman.github.io/randomnerd_esp32_wifi_manager/Touch_Electra-Electra_Touch/

**Comment by Bodmer** [comment]
Thanks I will take a look.

**Comment by ldijkman** [comment]
Hello

not 100% sure
but i think this stopped the rebooting at random times

// ESP8266 4MByte 12E 12F
  //bool parsed = ow.getForecast(current, hourly, daily, api_key, latitude, longitude, units, language, true); // looks like this causes reboots with Electra/Bodmer OW combined code
  bool parsed = ow.getForecast(current, hourly, daily, api_key, latitude, longitude, units, language, false); // last parameter == secure was true == looks like no reboots

https://github.com/ldijkman/randomnerd_esp32_wifi_manager/tree/main/ESP8266-TFT_eSPI

https://github.com/ldijkman/randomnerd_esp32_wifi_manager/tree/main/ESP8266-TFT_eSPI/ESP8266-LittleFS-wifi-manager_with_editor

**Comment by Bodmer** [comment]
OK, there is not much I can do about that. I see an issue has been raised on the ESP8266 board package tht relates to this porblem.

The ESP8266 relatively little RAM (~40kbytes for user sketches) for a relatively complex task like this, so I suspect expanding the code has meant that the stack and heap collide in certain circumstances. I think the ESP8266 is being pushed to do things it is not really able to handle.

There is an alternative set of data structures that reduce RAM needs here but I doubt the reduction will be sufficient to give a safe free RAM margin in all cases. I have just tried the ESP32 C3 and it has 390K available.

**Comment by ldijkman** [comment]
Thank you for your answers and fast response
Looking into the stack heap collision
My knowledge about the inner mcu/code working is low

I started with esp32
Then switched to esp8266
Because i could not find examples/libraries
Espasyncwebserver-littlefs-fsbrowser/webeditor

Thank you for your time
I Like tft espi and all the examples
