### ISSUE TITLE
OW HTTP header timeout

### ISSUE THREAD

**Issue by pbbco** [Bodmer/OpenWeather#43]
Hi Bodmer,
I'm building a 'weather globe' (i.e. LCD display and addressable LEDs and pillow stuffing inside a snow globe) using a Sparkfun ESP32 Thing and based on your BRILLIANT OW and TFT_espi Libs (thank you for those!!).  I've heavily modified the OW display and I've modified the OW lib to grab more info.
But I have occasional HTTP header timeout problems when I call the OW API.  If I paste the same URL into a browser I get the response immediately.  Changing the timeout in the OpenWeather.cpp doesn't seem to help.
example URL
https://api.openweathermap.org/data/2.5/onecall?lat=16.5361&lon=8.3146&exclude=minutely&units=imperial&lang=en&appid=APIKEY

I barely know what I'm doing here, so I don't even know where to start to see why there would be a difference between the ESP32 and a browser.
Unfortunately, the retries I've built in sometimes blow up the free OW account.
Any help would be greatly appreciated!
Thanks again for all your awesome libs.
pb

**Comment by Bodmer** [comment]
There are some options in a file inside the library folder to get some debug info sent to the serial port. See here:
https://github.com/Bodmer/OpenWeather/blob/master/User_Setup.h#L15-L16

Just uncomment the lines to see what the server is sending.

**Comment by Bodmer** [comment]
Assumed resolved.
