### ISSUE TITLE
humidity shows wrong value

### ISSUE THREAD

**Issue by PE5PVB** [Bodmer/OpenWeather#46]
Hi,

Can you please check the reported value for humidity. I guess this is in %, the current shown value is off with the one shown on the openweather website.

**Comment by Bodmer** [comment]
If you uncoment this line, compile and upload then the JSON being sent by the server is visible in the serial monitor window. 

https://github.com/Bodmer/OpenWeather/blob/master/User_Setup.h#L16

This is human readable JSON so you can see the values being reported.

**Comment by PE5PVB** [comment]
Did it. Looks like openweather sends some faulty info. When I use a script with City and Country definition, then the info is OK. Maybe I did something wrong with long/lat? I used google maps, search my location and used the right mousebutton to show the coordinates. Is this the correct way?

**Comment by Bodmer** [comment]
Yes, that should work. Make sure you get the lat, long +/- sign correct too.
