### ISSUE TITLE
ScreenGrabServer

### ISSUE THREAD

**Issue by Andrejkos** [Bodmer/OpenWeather#47]
Ошибка при компиляции скетча TFT_eSPI_OpenWeather - **_'screenServer' was not declared in this scope_**
 Я хочу использовать ScreenGrabServer
Error compiling sketch TFT_eSPI_OpenWeather - **_'screen Server' was not declared in this scope_**
 I want to use Screen Grab Server
[error.txt](https://github.com/Bodmer/OpenWeather/files/9410120/error.txt)
.

**Comment by Bodmer** [comment]
Support sketch is here:

https://github.com/Bodmer/OpenWeather/blob/master/examples/TFT_eSPI_OpenWeather/ScreenGrabServer.ino#L56
