### ISSUE TITLE
JSON_Decoder.h: No such file or directory

### ISSUE THREAD

**Issue by ZeekWorld** [Bodmer/OpenWeather#48]
Hello, I am trying to upload the project to a ESP8266, I have installed the mentioned json-streaming-parsey.zip on arduino but I am getting the following error.
Any help would be appreciated, thank you, Zeek

/Users/zeek/Downloads/OpenWeather-master/My_OpenWeather_Test/My_OpenWeather_Test.ino:27:10: fatal error: JSON_Decoder.h: No such file or directory
   27 | #include <JSON_Decoder.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: JSON_Decoder.h: No such file or directory

**Comment by Bodmer** [comment]
Check you can see the JSON_Decoder library examples in the IDE menu. This will be visible if the  JSON_Decoder library is installed correctly.

**Comment by ZeekWorld** [comment]
will do thanks.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by ZeekWorld** [comment]
Well, I have the project 90% up and running, the only thing I am having a hard time is with the icons, no icons displaying on the screen, if you can point me in the right direction how to get these display I would appreciate it!!!

**Comment by Bodmer** [comment]
You must allocate about 2Mbytes to LittleFS in the IDE, then use the upload option in the IDE to upload the icons to LittleFS.  Then upload the sketch again. Check ESP8266 documentation for more detailed LittleFS upload instructions and tool installation.

**Comment by ZeekWorld** [comment]
Done! All working, thank you for your help.

**Comment by Bodmer** [comment]
Glad you have it working.
