### ISSUE TITLE
Corrections to My_OpenWeather_Test.ino

### ISSUE THREAD

**Issue by mats-nk** [Bodmer/OpenWeather#56]
Hi,
I have been playing around with openweather and I really appreciate your work, saves me a ton.

But in `My_OpenWeather_Test.ino` there are some minor errors in the printout, a missing "`ln`" in `Serial.print` causes the output to be a bit messy.

There is also some in `OpenWeather.cpp`, but I take that in the next step.

I have included a corrected `My_OpenWeather_Test.ino` version.

/Mats

[My_OpenWeather_Test.ino.txt](https://github.com/Bodmer/OpenWeather/files/10509435/My_OpenWeather_Test.ino.txt)

**Comment by mats-nk** [comment]
Suggested change to OpenWeather.cpp to remove some cosmetic in the output.

I have added some `Serial.println("");` and changed one `print` to `println`.

[OpenWeather2.cpp.txt](https://github.com/Bodmer/OpenWeather/files/10513316/OpenWeather2.cpp.txt)

**Comment by Bodmer** [comment]
Updated, thanks.
