### ISSUE TITLE
New feature. OpenWeatherMap is deprecating "city"

### ISSUE THREAD

**Issue by mats-nk** [Bodmer/OpenWeather#57]
OpenWeatherMap is deprecation city as a parameter in the API and has introduced Geocoding API, [https://openweathermap.org/api/geocoding-api](https://openweathermap.org/api/geocoding-api).

Geocoding API will :

- [Direct geocoding](https://openweathermap.org/api/geocoding-api#direct) converts the specified name of a location or zip/post code into the exact geographical coordinates;

- [Reverse geocoding](https://openweathermap.org/api/geocoding-api#reverse) converts the geographical coordinates into the names of the nearby locations.

So by including geocoding you can combine that with Openweathermap and get the weather for a location instead of "long/lat".

**Comment by Bodmer** [comment]
The geocoding apears to simple respond with a lat and long based on the input city name.  If the user didi not input the required data in the correct format then this would lead to runtime problems that the user would not be able to figure out what went wrong. To handle all the error cases would be tricky.

The weather fetch API always requires lat and long so this is simple for  a user to obtain from Google or Google maps.

If you can figure out a simple way of using the api and integrating into the library then do post a pull request.
