### ISSUE TITLE
TFT_eSPI_OpenWeather

### ISSUE THREAD

**Issue by digitongithub** [Bodmer/OpenWeather#6]
Since you are mentioned everywhere in these types of projects please comment on the following.
I've been trying to make a forecast for a while. Now I have the TFT_eSPI_OpenWeather to the point where it is presented on display. However, the symbols and fonts give an error.
I was able to upload it successfully (arduino1.8), but it immediately gives the following error in the monitor

E (364) SPIFFS: mount failed, -10025

SPIFFS files found:
Listing directory: /
Failed to open directory

Font file fonts/NotoSansBold15 not found!
.

NTP response time was : 9 ms
Time since last sync is: 6.53 s
Received NTP UTC time : 8:12:00
Font file fonts/NotoSansBold15 not found!
Font file fonts/NotoSansBold15 not found!

I tried everything with and without SD card and both the complete data folder on the SD or just the fonts folder. I would love to know what I'm doing wrong now.

Thanks in advance for any response you can give

With regards Ton

**Comment by Bodmer** [comment]
The library examples do not use an SD Card.

SPIFFS and LittleFS ue the processors FLASH (program memory).

**Comment by digitongithub** [comment]
I find it strenge that the upload off spiffs succesfull is and the detail monitor gives an error that it not find the font in the directory. Thanx for the support With regards tonVerzonden vanaf mijn Galaxy
-------- Oorspronkelijk bericht --------Van: Bodmer ***@***.***> Datum: 13-03-23  11:27  (GMT+01:00) Aan: Bodmer/OpenWeather ***@***.***> Cc: digitongithub ***@***.***>, Author ***@***.***> Onderwerp: Re: [Bodmer/OpenWeather] TFT_eSPI_OpenWeather (Issue #6) 
The library examples do not use an SD Card.
SPIFFS and LittleFS ue the processors FLASH (program memory).

**Comment by Bodmer** [comment]
The sequence to follow is:
1. Set the SPIFFS partition size > 1 MByte
2. Upload the files
3. Upload the sketch

Make sure the sketch folder contains a "data" folder that contains the icon images. These will then be uploaded in srep 2.

The SPIFFS library has examples to try that will show SPIFFS is working on your setup.

**Comment by digitongithub** [comment]
Thank you many times for your response. What you say is exactly what I have done. Must use arduino 1.8 for upload data because the 2 version does not work. I emptied my Temp directory and then in combination with arduino 1.8 and version 2 I have the display with the icons.
The only thing I have to figure out is why the time is right but the date of the weather is not. Is on Jan 1 1.00. The api key works for other projects, so it should be good.

**Comment by digitongithub** [comment]
I have 1 more small question. With 1 esp32 I was able to load the code in arduino 1.8, but I have several new esp 32 modules and they all give an error with arduino 1.8. With Arduino 2, the codes do work. Since I want to upload the that (which works well) I also want to try to load the code, because otherwise it won't work at all. Suggestion??
