### ISSUE TITLE
Esptool Arduino 1.8 missing

### ISSUE THREAD

**Issue by digitongithub** [Bodmer/OpenWeather#7]
Find out why often the program cannot be loaded. I constantly lose the esptool in version 1.8. I also use the Version 2 and there it is. Do you have an idea how I can also use the esptool in version 1.8?

**Comment by Bodmer** [comment]
That is not part of this library and I am unable to help.

**Comment by digitongithub** [comment]
Thanx for support. I look how i can solve this.
