### ISSUE TITLE
getForecast URL Status Code

### ISSUE THREAD

**Issue by 1CM69** [Bodmer/OpenWeather#8]
Hi,
firstly, thanks for your OpenWeather library, much simpler using this than ArduinoJSON parsing.

OK, my sketch is getting data from a number of sources & on the others I use the HTTPClient & I check the status of the `HTTP.GET();` and direct to another page on my Nextion if the HTTP status code is  < 0 i.e. does not equal 200.

How am I able to get the HTTP status code of the ow.getForecast URL in my sketch.

Thanks

**Comment by 1CM69** [comment]
OK, I think I have found an answer but not using HTTP status codes

`bool owStatus = ow.getForecast(current, hourly, daily, OpenWeatherKey, latitude, longitude, units, language);


  if (!owStatus) {
    ReadForecastFailed();
  }
 else {
    //HANDLE THE PARSED DATA
}`

**Comment by Bodmer** [comment]
The library ignores the header so a library modification would be needed.
