### ISSUE TITLE
tinygsm compatibility

### ISSUE THREAD

**Issue by mokerosan** [Bodmer/OpenWeather#9]
Hello Bodmer, congratulations on your fantastic library, I am currently trying to connect your library with a sim800l module to send the request to the openweathermap api since I do not have a wifi connection, is it possible to do it with your library? have you tried it?

thanks!

**Comment by Bodmer** [comment]
This is not something I have tried. You would need to see if the SIM800 library supports the calls needed to request the data and provide the JSON stream.

I am unable to advise further.
